name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

jobs:
  docs:
    name: Generate crate documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # pin@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # pin@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Generate documentation
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # pin@v1
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"
        with:
          command: doc
          args: --workspace --no-deps

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@bd8c6b06eba6b3d25d72b7a1767993c0aeee42e7 # pin@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          force_orphan: true
