name: Tag

on:
  repository_dispatch:
    types: [tag-main]

  workflow_call:
    inputs:
      sui_commit:
        description: 'Sui repo commit to tag'
        type: string
        required: true
      tag_name:
        description: 'Tag Name'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      sui_commit:
        description: 'Sui repo commit to tag'
        type: string
        required: true
      tag_name:
        description: 'Tag Name'
        type: string
        required: true

env:
  SUI_COMMIT: "${{ github.event.client_payload.sui_commit || github.event.inputs.sui_commit }}"
  TAG_NAME: "${{ github.event.client_payload.tag_name || github.event.inputs.tag_name }}"

jobs:
  tag:
    name: Tag
    runs-on: [self-hosted, self-hosted-arc]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Tag
      uses: julbme/gh-action-manage-tag@v1
      with:
        name: ${{ env.TAG_NAME }}
        state: present
        from: ${{ env.SUI_COMMIT }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}