[package]
name = "narwhal-consensus"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
bincode = "1.3.3"
bytes = "1.3.0"
match_opt = "0.1.2"
rand = { version = "0.8.5", optional = true }
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1.0.35"
tokio = { workspace = true, features = ["sync"] }
tracing = "0.1.36"

config = { path = "../config", package = "narwhal-config" }
fastcrypto.workspace = true
crypto = { path = "../crypto", package = "narwhal-crypto" }
storage = { path = "../storage", package = "narwhal-storage" }
dag = { path = "../dag", package = "narwhal-dag" }
prometheus = "0.13.3"
types = { path = "../types", package = "narwhal-types" }
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }
cfg-if = "1.0.0"
mysten-metrics = { path = "../../crates/mysten-metrics" }
mysten-util-mem.workspace = true
store = { path = "../../crates/typed-store", package = "typed-store" }
telemetry-subscribers.workspace = true

[dev-dependencies]
bincode = "1.3.3"
criterion = "0.4.0"
futures = "0.3.24"
indexmap = { version = "1.9.2", features = ["serde"] }
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
node = { path = "../node", package = "narwhal-node" }

[target.'cfg(unix)'.dev-dependencies]
pprof = { version = "0.11.0", features = ["criterion", "flamegraph"]}

[features]
default = ["rand"]
benchmark = []
pprof = []

[lib]
bench = false

[[bench]]
name = "process_certificates"
harness = false
required-features = ["benchmark", "pprof"]
