[package]
name = "sui-verifier"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for Sui platform"
license = "Apache-2.0"
publish = false

[dependencies]
move-binary-format.workspace = true
move-bytecode-verifier.workspace = true
move-core-types.workspace = true

sui-types = { path = "../sui-types" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
