[package]
name = "sui-move"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
serde = { version = "1.0.144", features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
tracing = "0.1.36"
clap = { version = "3.2.17", features = ["derive"] }
serde_json = "1.0.88"
serde_yaml = "0.8.26"
git-version = "0.3.5"
const-str = "0.5.3"

sui-framework = { path = "../sui-framework" }
sui-framework-build = { path = "../sui-framework-build" }
sui-types = { path = "../sui-types" }


fastcrypto.workspace = true
colored = "2.0.0"

telemetry-subscribers.workspace = true

move-core-types.workspace = true
move-prover.workspace = true
move-prover-boogie-backend.workspace = true
move-stackless-bytecode.workspace = true
move-unit-test.workspace = true
move-cli.workspace = true
move-package.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemalloc-ctl = "^0.5"

[dev-dependencies]
tempfile = "3.3.0"
futures = "0.3.23"
prometheus = "0.13.3"

jsonrpsee = { version = "0.16.2", features = ["jsonrpsee-core"] }

test-utils = { path = "../test-utils" }
rand = "0.8.5"
move-package.workspace = true
sui-core = { path = "../sui-core" }
sui-node = { path = "../sui-node" }
sui-macros = { path = "../sui-macros" }
sui-simulator = { path = "../sui-simulator" }
mysten-metrics = { path = "../mysten-metrics" }

assert_cmd = "2.0.6"

[package.metadata.cargo-udeps.ignore]
normal = ["jemalloc-ctl"]

[features]
default = []
build = []
coverage = []
disassemble = []
prove = []
unit_test = []
calibrate = []
all = ["build", "coverage", "disassemble", "prove", "unit_test", "calibrate"]