[package]
name = "narwhal-dag"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[dependencies]
arc-swap = "1.5.1"
fastcrypto.workspace = true
dashmap = "5.4.0"
either = "1.8.0"
itertools = "0.10.5"
once_cell = "1.16"
rayon = "1.5.3"
serde = "1.0.144"
thiserror = "1.0.35"
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }

crypto = { path = "../crypto", package = "narwhal-crypto" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
rayon = "1.5.3"
