[package]
name = "sui-tool"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anemo.workspace = true
anyhow = { version = "1.0.64", features = ["backtrace"] }
tokio = { workspace = true, features = ["full"] }
tracing = "0.1.36"
clap = { version = "4.1.4", features = ["derive"] }

mysten-network.workspace = true
itertools = { version = "0.10.3", features = ["use_alloc"] }
multiaddr = "0.17.0"
textwrap = "0.16"
futures = "0.3.23"
rocksdb = "0.20.1"
tempfile = "3.3.0"
serde_with = { version = "2.1.0", features = ["hex"] }
strum_macros = "^0.24"
strum = "0.24.1"
serde = { version = "1.0.144", features = ["derive"] }
eyre = "0.6.8"
ron = "0.8.0"

narwhal-types = { path = "../../narwhal/types" }
sui-storage = { path = "../sui-storage" }
sui-core = { path = "../sui-core" }
sui-config = { path = "../sui-config" }
sui-types = { path = "../sui-types" }
sui-network = { path = "../sui-network" }

anemo-cli.workspace = true
telemetry-subscribers.workspace = true
typed-store.workspace = true

colored = "2.0.0"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
