[package]
name = "sui-macros"
version = "0.7.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
sui-proc-macros = { path = "../sui-proc-macros" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
once_cell = "1.16"
