[package]
name = "sui-open-rpc"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
schemars = "0.8.10"
serde = "1.0.141"
serde_json = "1.0.88"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
bcs = "0.1.3"
versions = "4.1.0"

[dev-dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
clap = { version = "3.2.17", features = ["derive"] }
pretty_assertions = "1.2.0"
tokio = { workspace = true, features = ["full"] }
fastcrypto = { workspace = true }
sui = { path = "../sui" }
sui-core = { path = "../sui-core"}
sui-json-rpc = { path = "../sui-json-rpc" }
sui-json-rpc-types = { path = "../sui-json-rpc-types" }
sui-json = { path = "../sui-json" }
sui-types = { path = "../sui-types" }
rand = "0.8.5"

move-core-types.workspace = true

[[example]]
name = "generate-json-rpc-spec"
path = "src/generate_json_rpc_spec.rs"
test = false
