[package]
name = "sui-framework-build"
version = "0.0.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for sui platform"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
fastcrypto = { workspace = true }
once_cell = "1.16"
tempfile = "3.3.0"
expect-test = "1.4.0"

serde-reflection = "0.3.6"
sui-types = { path = "../sui-types" }
sui-verifier = { path = "../../crates/sui-verifier" }

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-package.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }
