[book]
title = "Sui Move by Example"
description = "Handy collection of examples for Sui blockchain, made with love by Mysten Labs."
authors = ["damirka"]
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/MystenLabs/sui"
git-repository-icon = "fa-github"
