[package]
name = "sui-adapter"
version = "0.1.0"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Adapter and accompanying CLI for local sui development"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
bcs = "0.1.4"
leb128 = "0.2.5"
once_cell = "1.16"
linked-hash-map = "0.5.6"
tracing = "0.1.36"
serde = { version = "1.0.140", features = ["derive"] }

move-binary-format.workspace = true
move-bytecode-verifier.workspace = true
move-core-types.workspace = true
move-vm-runtime.workspace = true
move-vm-types.workspace = true

sui-framework = { path = "../sui-framework" }
sui-json = { path = "../sui-json" }
sui-verifier = { path = "../sui-verifier" }
sui-types = { path = "../sui-types" }
sui-cost-tables = { path = "../sui-cost-tables"}
sui-protocol-config = { path = "../sui-protocol-config" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
move-package.workspace = true
