[package]
name = "sui-rosetta"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
axum = "0.6.2"
axum-extra = "0.4.2"
anyhow = { version = "1.0.64", features = ["backtrace"] }
tracing = "0.1.36"
serde = "1.0.143"
serde_json = { version = "1.0.88", features = ["preserve_order", "arbitrary_precision"] }
tower = { version = "0.4.12", features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { version = "0.3.4", features = ["cors"] }
tokio = { workspace = true }
futures-core = "0.3.21"
futures = "0.3.23"
once_cell = "1.16"
serde_with = "2.1.0"
signature = "1.6.0"
bcs = "0.1.4"
hyper = "0.14.20"
strum = "0.24.1"
strum_macros = "0.24.3"
async-trait = "0.1.61"
clap = { version = "3.2.17", features = ["derive"] }
thiserror = "1.0.37"
eyre = "0.6.8"
rocksdb = "0.20.1"
typed-store.workspace = true
typed-store-derive.workspace = true
tempfile = "3.3.0"
fastcrypto.workspace = true
sui-types = { path = "../sui-types" }
sui-core = { path = "../sui-core" }
sui-sdk = { path = "../sui-sdk" }
sui-node = { path = "../sui-node" }
sui-config = { path = "../sui-config" }
sui-keys = { path = "../sui-keys" }
sui-storage = { path = "../sui-storage" }
mysten-metrics = { path = "../mysten-metrics" }
chrono = "0.4.23"

move-core-types.workspace = true

telemetry-subscribers.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
sui-sdk = { path = "../sui-sdk" }
sui-framework = { path = "../sui-framework" }
sui-framework-build = { path = "../sui-framework-build" }
test-utils = { path = "../test-utils" }
tempfile = "3.3.0"
rand = "0.8.5"
reqwest = { version = "0.11.13", default_features= false, features = ["rustls-tls"] }
