---
version: "3.9"
services:
  fullnode:
    image: mysten/sui-node:stable
    ports:
    - "9000:9000"
    - "9184:9184"
    expose:
    - "9000"
    - "9184"
    volumes:
    - ./fullnode-template.yaml:/sui/fullnode.yaml:ro
    - ./genesis.blob:/sui/genesis.blob:ro
    - suidb:/sui/suidb:rw
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
volumes:
  suidb:
