[package]
name = "sui-json-rpc-types"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.61"
anyhow = "1.0.64"
fastcrypto.workspace = true
fastcrypto-tbls.workspace = true
schemars = { version = "0.8.10", features = ["either"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.88"
serde_with = { version = "2.1.0", features = ["hex"] }
colored = "2.0.0"
either = "1.7.0"
itertools = "0.10.5"
tracing = "0.1.36"
bcs = "0.1.4"
bincode = "1.3.3"
sui-protocol-config = { path = "../sui-protocol-config" }

move-binary-format.workspace = true
move-core-types.workspace = true
move-bytecode-utils.workspace = true

sui-types = { path = "../sui-types" }
sui-json = { path = "../sui-json" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
