[package]
name = "mysten-metrics"
version = "0.7.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
workspace-hack = { version = "0.1", path = "../workspace-hack" }
tracing = "0.1"
scopeguard = "1"
prometheus = "0.13"
once_cell = "1"
tap = "1.0"
tokio.workspace = true
dashmap = "5.4.0"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"]}
parking_lot = "0.12.1"
futures = "0.3.23"

prometheus-closure-metric = { path = "../prometheus-closure-metric" }
