[package]
name = "sui-adapter-transactional-tests"
version = "0.1.0"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Transactional tests for Sui Adapter"
license = "Apache-2.0"
publish = false
edition = "2021"

[dev-dependencies]
datatest-stable = "0.1.2"
sui-transactional-test-runner = { path = "../sui-transactional-test-runner" }

[[test]]
name = "tests"
harness = false

[dependencies]
workspace-hack = { version = "0.1", path = "../workspace-hack" }
