[package]
name = "sui-telemetry"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
serde = { version = "1.0.144", features = ["derive"] }
reqwest = { version = "0.11.13", default_features= false, features = ["json", "rustls-tls"] }
tokio = { workspace = true, features = ["full", "tracing"] }
tracing = "0.1.36"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
