[package]
name = "sui-test-validator"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
clap = { version = "3.2.17", features = ["derive"] }
serde = "1.0.141"
serde_json = "1.0.88"
tokio = { workspace = true, features = ["full"] }
axum = { version = "0.6.2", features = ["json"] }
tower = { version = "0.4.12", features = ["util", "timeout", "load-shed", "limit"] }
tower-http = { version = "0.3.4", features = ["cors"] }
http = { version = "0.2.8" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

sui = { path = "../sui" }
sui-faucet = { path = "../sui-faucet" }
sui-cluster-test = { path = "../sui-cluster-test" }
sui-types = { path = "../sui-types" }
telemetry-subscribers.workspace = true

move-package.workspace = true
