[package]
name = "sui-protocol-config"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
workspace-hack = { version = "0.1", path = "../workspace-hack" }
serde = { version = "1.0.144", features = ["derive"] }
schemars = "0.8.10"
tracing = "0.1.36"
