[package]
name = "sui-source-validation"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
thiserror = "1.0.34"
futures = "0.3.25"

sui-types = { path = "../sui-types" }
sui-sdk = { path = "../../crates/sui-sdk" }
sui-framework = { path = "../../crates/sui-framework" }
sui-framework-build = { path = "../../crates/sui-framework-build" }

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-bytecode-verifier.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-package.workspace = true
move-symbol-pool.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]

expect-test = "1.4.0"
rand = "0.8.5"
tempfile = "3.3.0"
tokio = { version = "1.20.1", features = ["macros", "test-util"] }
tracing = "0.1.36"

sui = { path = "../sui" }
test-utils = { path = "../test-utils" }
