[package]
name = "mysten-network"
version = "0.2.0"
license = "Apache-2.0"
edition = "2021"
authors = ["Brandon Williams <brandon@mystenlabs.com>"]
description = "Mysten's network tooling"
publish = false

[dependencies]
bincode = "1.3.3"
bytes = "1.3.0"
eyre = "0.6.8"
futures = "0.3.21"
http = "0.2.8"
multiaddr = "0.17.0"
serde = { version = "1.0.140", features = ["derive"] }
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
tokio-stream = { version = "0.1.11", features = ["net"] }
tonic = { version = "0.8.2", features = ["transport"] }
tonic-health = "0.8.0"
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.3.4", features = ["trace", "set-header", "propagate-header"] }
tracing = "0.1.37"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
