[package]
name = "narwhal-node"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
async-trait = "0.1.61"
bincode = "1.3.3"
bytes = "1.3.0"
cfg-if = "1.0.0"
clap = "2.34"
futures = "0.3.24"
multiaddr = "0.17.0"
rand = "0.8.5"
thiserror = "1.0.35"
tokio = { workspace = true, features = ["full"] }
tokio-stream = "0.1.10"
tokio-util = { version = "0.7.4", features = ["codec"] }
tracing = "0.1.36"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.15", features = ["time", "env-filter"] }
url = "2.3.1"
axum = "0.6.2"
itertools = "0.10.5"
tonic = "0.8.2"
serde_json = "1.0.88"
config = { path = "../config", package = "narwhal-config" }
consensus = { path = "../consensus", package = "narwhal-consensus" }
fastcrypto.workspace = true
crypto = { path = "../crypto", package = "narwhal-crypto" }
executor = { path = "../executor", package = "narwhal-executor" }
network = { path = "../network", package = "narwhal-network" }
primary = { path = "../primary", package = "narwhal-primary" }
prometheus = "0.13.3"
storage = { path = "../storage", package = "narwhal-storage" }
types = { path = "../types", package = "narwhal-types" }
worker = { path = "../worker", package = "narwhal-worker" }
eyre = "0.6.8"
sui-keys = { path = "../../crates/sui-keys" }
sui-types = { path = "../../crates/sui-types" }

mysten-metrics = { path = "../../crates/mysten-metrics" }
store = { path = "../../crates/typed-store", package = "typed-store" }
mysten-network.workspace = true
telemetry-subscribers.workspace = true
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }

anemo.workspace = true
reqwest = { version = "0.11.13", default_features= false, features = ["json", "rustls-tls"] }
once_cell = "1.16.0"
fail = "0.5.1"

prost = "0.11"


[dev-dependencies]
pretty_assertions = "1.3.0"
serde-reflection = "0.3.6"
serde_yaml = "0.8.26"
structopt = "0.3.26"
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }

[features]
benchmark = ["worker/benchmark", "primary/benchmark", "consensus/benchmark"]
trace_transaction = ["worker/trace_transaction"]

[[bin]]
name = "narwhal-node"
path = "src/main.rs"

[[bin]]
name = "narwhal-benchmark-client"
path = "src/benchmark_client.rs"
required-features = ["benchmark"]

[[example]]
name = "narwhal-generate-format"
path = "src/generate_format.rs"
test = false
