[package]
name = "x"
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.64"
nexlint = { git = "https://github.com/nextest-rs/nexlint.git", rev = "94da5c787636dad779c340affa65219134d127f5" }
nexlint-lints = { git = "https://github.com/nextest-rs/nexlint.git", rev = "94da5c787636dad779c340affa65219134d127f5" }
clap = { version = "3.2.17", features = ["derive"] }
