[package]
name = "narwhal-primary"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.65"
arc-swap = "1.5.1"
async-trait = "0.1.61"
backoff = { version = "0.4", features = ["futures", "futures-core", "pin-project-lite", "tokio", "tokio_1"] }
base64 = "0.13.0"
bincode = "1.3.3"
bytes = "1.3.0"
config = { path = "../config", package = "narwhal-config" }
dashmap = "5.4.0"
derive_builder = "0.12.0"
futures = "0.3.24"
governor = "0.5.1"
itertools = "0.10.5"
multiaddr = "0.17.0"
once_cell = "1.16"
parking_lot = "0.12.1"
prometheus = "0.13.3"
prost = "0.11.3"
rand = { version = "0.8.5", features = ["small_rng"] }
roaring = "0.10.1"
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1.0.35"
tokio = { workspace = true, features = ["sync", "rt", "macros", "time", "test-util"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tonic = "0.8.2"
tower = { version = "0.4.13", features = ["full"] }
tracing = "0.1.36"
tap = "1.0.1"


consensus = { path = "../consensus", package = "narwhal-consensus" }
fastcrypto.workspace = true
crypto = { path = "../crypto", package = "narwhal-crypto" }
network = { path = "../network", package = "narwhal-network" }
types = { path = "../types", package = "narwhal-types" }
storage = { path = "../storage", package = "narwhal-storage" }
store = { path = "../../crates/typed-store", package = "typed-store" }
mysten-network.workspace = true
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }

mysten-metrics = { path = "../../crates/mysten-metrics" }

anemo.workspace = true
anemo-tower.workspace = true
fail = "0.5.1"

[dev-dependencies]
dashmap = "5.4.0"
arc-swap = { version = "1.5.1", features = ["serde"] }
async-trait = "0.1.61"
executor = { path = "../executor", package = "narwhal-executor" }
indexmap = { version = "1.9.2", features = ["serde"] }
itertools = "0.10.5"
mockall = "0.11.2"
node = { path = "../node", package = "narwhal-node" }
proptest = "1.0.0"
tempfile = "3.3.0"
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
thiserror = "1.0.35"
tracing = "0.1.36"
worker = { path = "../worker", package = "narwhal-worker" }
storage = { path = "../storage", package = "narwhal-storage" }
reqwest = { version = "0.11.13", default_features= false, features = ["json", "rustls-tls"] }
telemetry-subscribers = { path = "../../crates/telemetry-subscribers"}

[features]
benchmark = []
