version: "3.9"
networks:
  mec:
    external: true
    
services:
  # Setup for Validator 0. A primary node and a worker
  primary_0:
    image: mec-narwhal:latest
    environment:
      - NODE_TYPE=primary
      - VALIDATOR_ID=0
      - LOG_LEVEL=-vvv
      - EXECUTION_BLOCK_TYPE=hyperledger_fabric # ethereum or hyperledger_fabric

      # - CONSENSUS_DISABLED=--consensus-disabled
    expose:
      - "3000" # Port to listen on messages from other primary nodes
      - "3001" # Port to listen on messages from our worker nodes
    networks:
      mec: 
    ports:
      - "8000:8000" # expose the gRPC port to be publicly accessible
      - "8100:8010" # expose the port listening to metrics endpoint for prometheus metrics
    volumes:
      - ./validators:/validators
      - ./validators/validator-0/logs:/home/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==bsp-devel"
    hostname: primary_0
  worker_0:
    depends_on:
      - primary_0
    image: mec-narwhal:latest
    environment:
      - NODE_TYPE=worker
      - VALIDATOR_ID=0
      - LOG_LEVEL=-vvv
      - WORKER_ID=0
    expose:
      - "4000" # Port to listen on messages from our primary node
      - "4001" # Port to listen for transactions from clients
      - "4002" # Port to listen on messages from other worker nodes
    ports:
      - "7001:4001" # expose the port for the worker to accept transactions from clients
    networks:
      mec: 
    volumes:
      - ./validators:/validators
      - ./validators/validator-0/logs:/home/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==bsp-devel"
    hostname: worker_0
  # Setup for Validator 1. A primary node and a worker
  primary_1:
    image: mec-narwhal:latest
    environment:
      - NODE_TYPE=primary
      - VALIDATOR_ID=1
      - LOG_LEVEL=-vvv
      - EXECUTION_BLOCK_TYPE=hyperledger_fabric # ethereum or hyperledger_fabric

      # - CONSENSUS_DISABLED=--consensus-disabled
    expose:
      - "3000" # Port to listen on messages from other primary nodes
      - "3001" # Port to listen on messages from our worker nodes
    ports:
      - "8001:8000" # expose the gRPC port to be publicly accessible
      - "8101:8010" # expose the port listening to metrics endpoint for prometheus metrics
    networks:
      mec:    
    volumes:
      - ./validators:/validators
      - ./validators/validator-1/logs:/home/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==bsp-devel"
    hostname: primary_1
  worker_1:
    depends_on:
      - primary_1
    image: mec-narwhal:latest
    environment:
      - NODE_TYPE=worker
      - VALIDATOR_ID=1
      - LOG_LEVEL=-vvv
      - WORKER_ID=0
    expose:
      - "4000" # Port to listen on messages from our primary node
      - "4001" # Port to listen for transactions from clients
      - "4002" # Port to listen on messages from other worker nodes
    ports:
      - "7002:4001" # expose the port for the worker to accept transactions from clients
    networks:
      mec:     
    volumes:
      - ./validators:/validators
      - ./validators/validator-1/logs:/home/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==bsp-devel"
    hostname: worker_1
  # Setup for Validator 2. A primary node and a worker
  primary_2:
    image: mec-narwhal:latest
    environment:
      - NODE_TYPE=primary
      - VALIDATOR_ID=2
      - LOG_LEVEL=-vvv
      - EXECUTION_BLOCK_TYPE=hyperledger_fabric # ethereum or hyperledger_fabric
      # - CONSENSUS_DISABLED=--consensus-disabled
    expose:
      - "3000" # Port to listen on messages from other primary nodes
      - "3001" # Port to listen on messages from our worker nodes
    networks:
      mec:     
    ports:
      - "8002:8000" # expose the gRPC port to be publicly accessible
      - "8102:8010" # expose the port listening to metrics endpoint for prometheus metrics
    volumes:
      - ./validators:/validators
      - ./validators/validator-2/logs:/home/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==bsp-devel"
    hostname: primary_2
  worker_2:
    depends_on:
      - primary_2
    image: mec-narwhal:latest
    environment:
      - NODE_TYPE=worker
      - VALIDATOR_ID=2
      - LOG_LEVEL=-vvv
      - WORKER_ID=0
    expose:
      - "4000" # Port to listen on messages from our primary node
      - "4001" # Port to listen for transactions from clients
      - "4002" # Port to listen on messages from other worker nodes
    networks:
      mec:     
    ports:
      - "7003:4001" # expose the port for the worker to accept transactions from clients
    volumes:
      - ./validators:/validators
      - ./validators/validator-2/logs:/home/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==bsp-devel"
    hostname: worker_2
  # Setup for Validator 3. A primary node and a worker
  primary_3:
    image: mec-narwhal:latest
    environment:
      - NODE_TYPE=primary
      - VALIDATOR_ID=3
      - LOG_LEVEL=-vvv
      - EXECUTION_BLOCK_TYPE=hyperledger_fabric # ethereum or hyperledger_fabric
      # - CONSENSUS_DISABLED=--consensus-disabled
    expose:
      - "3000" # Port to listen on messages from other primary nodes
      - "3001" # Port to listen on messages from worker nodes
    networks:
      mec:     
    ports:
      - "8003:8000" # expose the gRPC port to be publicly accessible
      - "8103:8010" # expose the port listening to metrics endpoint for prometheus metrics
    volumes:
      - ./validators:/validators
      - ./validators/validator-3/logs:/home/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==bsp-devel"
    hostname: primary_3
  worker_3:
    depends_on:
      - primary_3
    image: mec-narwhal:latest
    environment:
      - NODE_TYPE=worker
      - VALIDATOR_ID=3
      - LOG_LEVEL=-vvv
      - WORKER_ID=0
    expose:
      - "4000" # Port to listen on messages from our primary node
      - "4001" # Port to listen for transactions from clients
      - "4002" # Port to listen on messages from other worker nodes
    networks:
      mec:     
    ports:
      - "7004:4001" # expose the port for the worker to accept transactions from clients
    volumes:
      - ./validators:/validators
      - ./validators/validator-3/logs:/home/logs
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.hostname==bsp-devel"
    hostname: worker_3
