[package]
name = "sui-swarm"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
rand = "0.8.5"
tracing = "0.1.36"
tokio = { workspace = true, features = ["full"] }
futures = "0.3.23"
tempfile = "3.3.0"
tonic-health = "0.8.0"
tap = "1.0.1"
prometheus = "0.13.3"

sui-config = { path = "../sui-config" }
sui-node = { path = "../sui-node" }
sui-protocol-config = { path = "../sui-protocol-config" }
sui-types = { path = "../sui-types" }
mysten-metrics = { path = "../mysten-metrics" }
mysten-network.workspace = true
telemetry-subscribers.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[target.'cfg(msim)'.dependencies]
sui-simulator = { path = "../sui-simulator" }

