[package]
name = "sui-sdk"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.64"
async-trait = "0.1.61"
jsonrpsee = { version = "0.16.2", features = ["http-client"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.88"
futures-core = "0.3.21"
futures = "0.3.23"
tokio = { workspace = true }
rand = "0.8.5"
bcs = "0.1.4"
thiserror = "1.0.37"

sui-adapter = { path = "../sui-adapter" }
sui-json-rpc = { path = "../sui-json-rpc" }
sui-transaction-builder = { path = "../sui-transaction-builder" }
sui-json-rpc-types= { path = "../sui-json-rpc-types" }
sui-types = { path = "../sui-types" }
sui-json = { path = "../sui-json" }
sui-config = { path = "../sui-config" }
sui-keys =  { path = "../sui-keys" }

move-core-types.workspace = true
move-bytecode-utils.workspace = true
move-binary-format.workspace = true
fastcrypto.workspace = true

workspace-hack= { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
clap = { version = "3.2.17", features = ["derive"] }
dirs = "4.0.0"
async-recursion = "1.0.0"
tempfile = "3.3.0"
test-utils = { path = "../test-utils" }
futures-core = "0.3.21"
futures = "0.3.23"
sui =  { path = "../sui" }

[[example]]
name = "tic-tac-toe"
path = "examples/tic_tac_toe.rs"
test = false
