[package]
name = "narwhal-worker"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
edition = "2021"
publish = false

[dependencies]
dashmap = "5.4.0"
async-trait = "0.1.61"
bincode = "1.3.3"
byteorder = "1.4.3"
bytes = "1.3.0"
futures = "0.3.24"
governor = "0.5.1"
multiaddr = "0.17.0"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0.144", features = ["derive"] }
tap = "1.0.1"
tokio = { workspace = true, features = ["sync", "rt", "macros"] }
tokio-stream = "0.1.10"
tokio-util = { version = "0.7.4", features = ["codec"] }
tonic = "0.8.2"
tower = "0.4.13"
tracing = "0.1.36"

config = { path = "../config", package = "narwhal-config" }
fastcrypto.workspace = true
crypto = { path = "../crypto", package = "narwhal-crypto" }
network = { path = "../network", package = "narwhal-network" }
types = { path = "../types", package = "narwhal-types" }
prometheus = "0.13.3"
store = { path = "../../crates/typed-store", package = "typed-store" }
mysten-network = { path = "../../crates/mysten-network"}

mysten-metrics = { path = "../../crates/mysten-metrics" }

anemo.workspace = true
anemo-tower.workspace = true
anyhow = "1.0.65"
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }
eyre = "0.6.8"

[dev-dependencies]
arc-swap = { version = "1.5.1", features = ["serde"] }
rand = "0.8.5"
tempfile = "3.3.0"
test-utils = { path = "../test-utils", package = "narwhal-test-utils" }
reqwest = { version = "0.11.13", default_features= false, features = ["json", "rustls-tls"] }
node = { path = "../node", package = "narwhal-node" }
consensus = { path = "../consensus", package = "narwhal-consensus" }
primary = { path = "../primary", package = "narwhal-primary" }
telemetry-subscribers = { path = "../../crates/telemetry-subscribers"}
storage = { path = "../storage", package = "narwhal-storage" }

[features]
benchmark = []
trace_transaction = []
