[package]
name = "sui-framework"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for sui platform"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
better_any = "0.1.1"
bcs = "0.1.4"
linked-hash-map = "0.5.6"
multiaddr = "0.17.0"
smallvec = "1.9.0"
once_cell = "1.16"
curve25519-dalek-ng = "4.1.1"
bincode = "1.3.3"

fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
fastcrypto-tbls.workspace = true

digest = "0.10.3"
serde = { version = "1.0.144", features = ["derive"] }

sui-framework-build = { path = "../sui-framework-build" }
sui-types = { path = "../sui-types" }

move-binary-format.workspace = true
move-bytecode-verifier.workspace = true
move-cli.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-package.workspace = true
move-stdlib.workspace = true
move-unit-test.workspace = true
move-vm-runtime.workspace = true
move-vm-test-utils.workspace = true
move-vm-types.workspace = true
narwhal-crypto = { path = "../../narwhal/crypto" }
sui-protocol-config = { path = "../sui-protocol-config" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[build-dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
bcs = "0.1.4"

sui-framework-build = { path = "../sui-framework-build" }

move-binary-format.workspace = true
move-package.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["move-cli", "move-unit-test"]
