[package]
name = "typed-store"
version = "0.4.0"
license = "Apache-2.0"
authors = ["Francois Garillot <francois@mystenlabs.com>"]
description = "a typed database interface"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
collectable = "0.0.2"
eyre = "0.6.8"
fdlimit = "0.2.1"
once_cell = "1.15.0"
tap = "1.0.1"
num_cpus = "1.14.0"
prometheus = "0.13.3"
hdrhistogram = "7.5.1"
# deactivation of bzip2 due to https://github.com/rust-rocksdb/rust-rocksdb/issues/609
rocksdb = { version = "0.20.1", features = ["snappy", "lz4", "zstd", "zlib", "multi-threaded-cf"], default-features = false }
serde = { version = "1.0.140", features = ["derive"] }
thiserror = "1.0.37"
tokio = { workspace = true, features = ["full", "test-util"] }
tracing = "0.1.37"
sui-macros = { path = "../sui-macros" }
ouroboros = "0.15.5"
rand = "0.8.5"
async-trait = "0.1.57"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
tempfile = "3.3.0"
once_cell = "1.13.0"
proc-macro2 = "1.0.47"
quote = "1.0.23"
rstest = "0.16.0"
rand = "0.8.5"
syn = { version = "1.0.104", features = ["derive"] }
typed-store-derive = {path = "../typed-store-derive"}

# Most packages should depend on sui-simulator instead of directly on msim, but for typed-store
# that creates a circular dependency.
[target.'cfg(msim)'.dependencies]
msim = { git = "https://github.com/MystenLabs/mysten-sim.git", rev = "888a9dc4331b0ed944bd6e37bac982bbcf0625d5", package = "msim" }
