[package]
name = "sui-config"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anemo.workspace = true
bcs = "0.1.4"
arc-swap = "1.5.1"
camino = "1.1.1"
anyhow = { version = "1.0.64", features = ["backtrace"] }
serde = { version = "1.0.144", features = ["derive", "rc"] }
serde_with = "2.1.0"
serde_yaml = "0.8.26"
rand = "0.8.5"
dirs = "4.0.0"
multiaddr = "0.17.0"
once_cell = "1.16"
tracing = "0.1.36"

fastcrypto.workspace = true
move-binary-format.workspace = true
move-package.workspace = true
move-core-types.workspace = true
move-vm-runtime.workspace = true
narwhal-config = { path = "../../narwhal/config" }
narwhal-crypto = { path = "../../narwhal/crypto" }

sui-framework = { path = "../sui-framework" }
sui-adapter = { path = "../sui-adapter" }
sui-types = { path = "../sui-types" }
sui-keys = { path = "../sui-keys" }
sui-protocol-config = { path = "../sui-protocol-config" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[target.'cfg(msim)'.dependencies]
sui-simulator = { path = "../sui-simulator" }

[dev-dependencies]
insta = { version = "1.21.1", features = ["redactions", "yaml"] }
tempfile = "3.3.0"
