[package]
name = "sui-types"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anemo.workspace = true
anemo-tower.workspace = true
anyhow = { version = "1.0.64", features = ["backtrace"] }
bincode = "1.3.3"
bcs = "0.1.4"
byteorder = "1.4.3"
itertools = "0.10.5"
once_cell = "1.16"
rand = "0.8.5"
serde = { version = "1.0.144", features = ["derive"] }
serde-name = "0.2.1"
thiserror = "1.0.34"
tracing = "0.1"
serde_bytes = "0.11.9"
serde_json = "1.0.88"
serde_with = "2.1.0"
serde_repr = "0.1"
signature = "1.6.0"
static_assertions = "1.1.0"
zeroize = "1.5.7"
schemars ="0.8.10"
tap = "1.0.1"
tonic = "0.8"
strum = "^0.24"
strum_macros = "^0.24"
roaring = "0.10.1"
enum_dispatch = "^0.3"
eyre = "0.6.8"
multiaddr = "0.17.0"

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-core-types.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true
move-vm-runtime.workspace = true
move-vm-types.workspace = true

narwhal-config = { path = "../../narwhal/config" }
narwhal-crypto = { path = "../../narwhal/crypto" }
sui-cost-tables = { path = "../sui-cost-tables"}
sui-protocol-config = { path = "../sui-protocol-config" }

fastcrypto = { workspace = true, features = ["copy_key"] }

typed-store.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }
derive_more = "0.99.17"

[dev-dependencies]
bincode = "1.3.3"
test-utils = { path = "../test-utils" }
criterion = { version = "0.4.0", features = ["async", "async_tokio"] }
proptest = "1.0.0"

[[bench]]
name = "accumulator_bench"
harness = false
