[package]
name = "telemetry-subscribers"
version = "0.2.0"
license = "Apache-2.0"
authors = ["Evan Chan <echan@mystenlabs.com>"]
description = "Library for common telemetry and observability functionality"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[dependencies]
console-subscriber = { version = "0.1.6", optional = true }
crossterm = "0.25.0"
once_cell = "1.13.0"
prometheus = "0.13.3"
tokio = { workspace = true, features = ["sync", "macros", "rt", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.15", features = ["std", "time", "json", "registry", "env-filter"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[features]
default = []
tokio-console = ["console-subscriber"]

[dev-dependencies]
camino = "1.0.9"
