[package]
name = "typed-store-derive"
version = "0.3.0"
license = "Apache-2.0"
authors = ["Ade A. <ade@mystenlabs.com>"]
description = "macros for the typed-store crate"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.47"
quote = "1.0.23"
syn = { version = "1.0.104", features = ["full"] }
workspace-hack = { version = "0.1", path = "../workspace-hack" }


[dev-dependencies]
eyre = "0.6.8"
rocksdb = { version = "0.20.1", features = ["snappy", "lz4", "zstd", "zlib", "multi-threaded-cf"], default-features = false }
tempfile = "3.3.0"
tokio = { workspace = true, features = ["test-util"] }
typed-store = { path = "../typed-store" }