[package]
name = "sui-storage"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait = "0.1.61"
bcs = "0.1.4"
enum_dispatch = "^0.3"
fdlimit = "0.2.1"
futures = "0.3.23"
flexstr = "^0.9"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.88"
tokio = { workspace = true, features = ["full", "tracing"] }
tokio-stream = "^0.1"
rocksdb = "0.20.1"
tracing = "0.1.36"
# patch sqlx to a version using libsqlite3-sys v0.25.1 or later, see
# https://github.com/launchbadge/sqlx/pull/2176
sqlx = { git = "https://github.com/huitseeker/sqlx", branch = "update_libsqlite3", features = [ "runtime-tokio-rustls", "sqlite" ] }
strum = "^0.24"
strum_macros = "^0.24"
anyhow = "1.0.64"
tempfile = "3.3.0"
tap = "1.0.1"

sui-simulator = { path = "../sui-simulator" }
sui-types = { path = "../sui-types" }
mysten-metrics = { path = "../mysten-metrics" }
move-core-types.workspace = true
move-bytecode-utils.workspace = true
sui-json-rpc-types = { path = "../sui-json-rpc-types" }
typed-store.workspace = true
typed-store-derive.workspace = true
telemetry-subscribers = { path = "../../crates/telemetry-subscribers"}
workspace-hack = { version = "0.1", path = "../workspace-hack" }
eyre = "0.6.8"

fastcrypto = { workspace = true, features = ["copy_key"] }

[dev-dependencies]
anyhow = "1.0.64"
criterion = { version = "0.4.0", features = ["async", "async_tokio"] }
tempfile = "3.3.0"
num_cpus = "1.14.0"
pretty_assertions = "1.2.0"
once_cell = "1.16"

[[bench]]
name = "write_ahead_log"
harness = false

[[bench]]
name = "event_store_bench"
harness = false
