[package]
name = "sui-open-rpc-macros"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.104", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
itertools = "0.10.5"
derive-syn-parse = "0.1.5"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
unescape = "0.1.0"
