[package]
name = "sui-tls"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Brandon Williams <brandon@mystenlabs.com>"]
description = "tools for rustls-based certificate generation and verification"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.69"
ed25519 = { version = "1.5.0", features = ["pkcs8", "alloc", "zeroize"] }
pkcs8 = { version = "0.9.0", features = ["std"] }
rcgen = "0.9.2"
rustls = { version = "0.20.4", features = ["dangerous_configuration"] }
tracing = "0.1.32"
webpki = { version = "0.22.0", features = ["alloc", "std"] }
x509-parser = "0.14.0"

fastcrypto.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

# reqwest support
reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls"] }

# Axum support
axum = "0.6.6"
axum-server = { version = "0.4.4", default-features = false, features = ["tls-rustls"] }
tokio-rustls = "0.23"
tower-layer = "0.3.2"
tokio.workspace = true

[dev-dependencies]
rand = "0.8.5"
