[package]
name = "narwhal-examples"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
publish = false
edition = "2021"

[[bin]]
name = "demo_client"
path = "src/demo_client.rs"

[dependencies]
base64 = "0.13.0"
clap = "2.34"
prost = "0.11.3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tonic = "0.8.2"
workspace-hack = { version = "0.1", path = "../../crates/workspace-hack" }

[target.'cfg(not(target_env = "msvc"))'.build-dependencies]
protobuf-src = "1.1.0"

[build-dependencies]
tonic-build = "0.8.2"

[features]
benchmark = []
