[package]
name = "sui-indexer"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"


[dependencies]
anyhow = { version = "1.0.64", features = ["backtrace"] }
async-trait = "0.1.61"
backoff = { version = "0.4", features = ["futures", "futures-core", "pin-project-lite", "tokio", "tokio_1"] }
chrono = { version = "0.4.23", features = [
  "clock",
  "serde",
] }
clap = { version = "3.2.17", features = ["derive"] }
diesel = { version = "2.0.0", features = ["chrono", "postgres", "r2d2", "serde_json"] }
futures = "0.3.23"
jsonrpsee = { version = "0.16.2", features = ["full"] }
jsonrpsee-proc-macros = "0.16.2"
serde = { version = "1.0.144", features = ["derive"] }
prometheus = "0.13.3"
serde_json = "1.0.83"
thiserror = "1.0.34"
tracing = "0.1.36"
tokio = { workspace = true, features = ["full"] }

mysten-metrics = { path = "../mysten-metrics" }
narwhal-network = { path = "../../narwhal/network" }
sui-config = { path = "../sui-config" }
sui-core = { path = "../sui-core" }
sui-json = { path = "../sui-json" }
sui-json-rpc = { path = "../sui-json-rpc" }
sui-json-rpc-types= { path = "../sui-json-rpc-types" }
sui-keys = { path = "../sui-keys" }
sui-node = { path = "../sui-node" }
sui-open-rpc = { path = "../sui-open-rpc" }
sui-open-rpc-macros = { path = "../sui-open-rpc-macros" }
sui-sdk = { path = "../sui-sdk" }
sui-types = { path = "../sui-types" }
telemetry-subscribers.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

fastcrypto = { workspace = true, features = ["copy_key"] }

[dev-dependencies]
test-utils = { path = "../test-utils" }
sui-framework-build = { path = "../sui-framework-build" }

[[bin]]
name = "sui-indexer"
path = "src/main.rs"
