[package]
name = "sui-simulator"
version = "0.7.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
workspace-hack = { version = "0.1", path = "../workspace-hack" }
sui-framework = { path = "../sui-framework" }
sui-framework-build = { path = "../sui-framework-build" }
sui-types = { path = "../sui-types" }
tempfile = "3.3.0"
tracing = "0.1"
anemo.workspace = true
anemo-tower.workspace = true
narwhal-network = { path = "../../narwhal/network" }
fastcrypto = { workspace = true, features = ["copy_key"] }
telemetry-subscribers.workspace = true
tower = "0.4.13"

[target.'cfg(msim)'.dependencies]
msim = { git = "https://github.com/MystenLabs/mysten-sim.git", rev = "888a9dc4331b0ed944bd6e37bac982bbcf0625d5", package = "msim" }
